http:
  port: 9000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  login:
    host: localhost
  product:
    host: localhost
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  test:
    url: 'http://localhost:7070'
  productService:
    url: 'http://localhost:8080'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  test:
    apiEndpoints:
      - login
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: test 
              changeOrigin: true    
  productService:
    apiEndpoints:
      - product
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: productService 
              changeOrigin: true    
